apiVersion: skaffold/v2beta9
kind: Config
metadata:
  name: bridge
build:
  artifacts:
    - image: registry.digitalocean.com/alog-rs/bridge
      docker:
        dockerfile: ./Dockerfile
deploy:
  helm:
    releases:
      - name: alog-bridge-dev
        chartPath: alog-bridge
        valuesFiles:
          - "./alog-bridge/values.yaml"
          - "./alog-bridge/values.development.yaml"
        artifactOverrides:
          image: registry.digitalocean.com/alog-rs/bridge

profiles:
  - name: alog-bridge-prod
    activation:
      - env: PRODUCTION_ENV=1
    patches:
      - op: replace
        path: /deploy/helm/releases/0/valuesFiles
        value:
          - "./alog-bridge/values.yaml"
          - "./alog-bridge/values.production.yaml"