apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      serviceAccountName: {{ .Values.spec.serviceAccountName }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image }}
          resources:
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: GRPC_PORT
              value: "{{ .Values.service.grpcPort }}"
